const MAIN_CATEGORY_INDICATOR_HEIGHT = 6;

export const heights = {
  TOP_BANNER_HEIGHT: 170,
  WALLET_HEIGHT: 78,
  NAVIGATION_HEADER_HEIGHT: 51,
  WALLET_OFFSET: -10,
  MAIN_CATEGORY_HEIGHT: 170 + MAIN_CATEGORY_INDICATOR_HEIGHT,
  MAIN_CATEGORY_INDICATOR_HEIGHT: MAIN_CATEGORY_INDICATOR_HEIGHT,
  PHOTO_PROMO_HEIGHT: 110,
  BIG_BRAND_DISCOUNT_HEIGHT: 400,
  SPACER_HEIGHT: 14,
  SHOCKING_SALE_HEIGHT: 240,
  SHOPEE_MALL_HEIGHT: 370,
  PRODUCT_HEIGHT: 230,
  SHOPEE_LIVE_HEIGHT: 250,
  DEALS_TOP_UP_BILLS_HEIGHT: 240,
  TRENDING_SEARCH_HEIGHT: 179,
  FEATURED_COLLECTION_HEIGHT: 230,
  MAIN_CATEGORIES_HEIGHT: 280,
  SECTION_HEADER_HEIGHT: 40,
  CATEGORY_SELECTOR_HEIGHT: 90,
};
